# Generated by Django 5.2.14 on 2026-05-07 16:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PriceAlert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254, verbose_name='Email')),
                ('ticker', models.CharField(max_length=10, verbose_name='Тікер')),
                ('target_price', models.FloatField(verbose_name='Цільова ціна')),
                ('condition', models.CharField(choices=[('above', 'Ціна підніметься вище'), ('below', 'Ціна впаде нижче')], max_length=10, verbose_name='Умова')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активне')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Сповіщення',
                'verbose_name_plural': 'Сповіщення',
            },
        ),
    ]
