# Generated by Django 5.2.14 on 2026-05-15 19:47

import analyzer.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analyzer', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SharedPortfolio',
            fields=[
                ('id', models.CharField(default=analyzer.models.generate_short_id, max_length=10, primary_key=True, serialize=False)),
                ('portfolio_type', models.CharField(max_length=20)),
                ('tickers', models.TextField()),
                ('sliders', models.JSONField(default=dict)),
                ('budget_amount', models.FloatField(default=0)),
                ('budget_currency', models.CharField(default='USD', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
